Vars double quoted to prevent globbing and word splitting.

diff --git a/startup/default-init.in b/startup/default-init.in
--- a/startup/default-init.in
+++ b/startup/default-init.in
@@ -39,16 +39,16 @@
 ### END INIT INFO
 
 # Our install-time configuration.
-NagiosBin=@bindir@/@nagios_name@
-NagiosCfgFile=@sysconfdir@/nagios.cfg
-NagiosCfgtestFile=@localstatedir@/nagios.configtest
-NagiosStatusFile=@localstatedir@/status.dat
-NagiosRetentionFile=@localstatedir@/retention.dat
-NagiosCommandFile=@localstatedir@/rw/nagios.cmd
-NagiosVarDir=@localstatedir@
-NagiosCGIDir=@sbindir@
-NagiosUser=@nagios_user@
-NagiosGroup=@nagios_grp@
+NagiosBin="@bindir@/@nagios_name@"
+NagiosCfgFile="@sysconfdir@/nagios.cfg"
+NagiosCfgtestFile="@localstatedir@/nagios.configtest"
+NagiosStatusFile="@localstatedir@/status.dat"
+NagiosRetentionFile="@localstatedir@/retention.dat"
+NagiosCommandFile="@localstatedir@/rw/nagios.cmd"
+NagiosVarDir="@localstatedir@"
+NagiosCGIDir="@sbindir@"
+NagiosUser="@nagios_user@"
+NagiosGroup="@nagios_grp@"
 checkconfig="true"
 
 # Source function library
@@ -67,15 +67,15 @@ if test -f /etc/sysconfig/nagios; then
 fi
 
 # Automate addition of RAMDISK based on environment variables
-USE_RAMDISK=${USE_RAMDISK:-0}
+USE_RAMDISK="${USE_RAMDISK:-0}"
 if test "$USE_RAMDISK" -ne 0 && test "$RAMDISK_SIZE"X != "X"; then
-	ramdisk=`mount |grep "${RAMDISK_DIR} type tmpfs"`
+	ramdisk="`mount |grep "${RAMDISK_DIR} type tmpfs"`"
 	if [ "$ramdisk"X == "X" ]; then
-		if [ ! -d ${RAMDISK_DIR} ]; then
-			mkdir -p -m 0755 ${RAMDISK_DIR}
-			if [ -d ${RAMDISK_DIR} ]; then
-				NagiosUserUID=`id -u ${NagiosUser}`
-				NagiosGroupGID=`id -g ${NagiosGroup}`
+		if [ ! -d "${RAMDISK_DIR}" ]; then
+			mkdir -p -m 0755 "${RAMDISK_DIR}"
+			if [ -d "${RAMDISK_DIR}" ]; then
+				NagiosUserUID="`id -u ${NagiosUser}`"
+				NagiosGroupGID="`id -g ${NagiosGroup}`"
 				mount -t tmpfs -o uid=${NagiosUserUID},gid={$NagiosGroupGID},size=${RAMDISK_SIZE}m tmpfs ${RAMDISK_DIR}
 				su ${NagiosUser} -c "mkdir -m 0755 ${RAMDISK_DIR}/checkresults"
 			else
@@ -105,25 +105,25 @@ check_config ()
 		exit 8
 	fi
 
-	TMPFILE=$(mktemp /tmp/.configtest.XXXXXXXX)
+	TMPFILE="$(mktemp /tmp/.configtest.XXXXXXXX)"
 	$NagiosBin -vp $NagiosCfgFile > "$TMPFILE"
-	WARN=`grep ^"Total Warnings:" "$TMPFILE" |awk -F: '{print \$2}' |sed s/' '//g`
-	ERR=`grep ^"Total Errors:" "$TMPFILE" |awk -F: '{print \$2}' |sed s/' '//g`
+	WARN="`grep ^"Total Warnings:" "$TMPFILE" |awk -F: '{print \$2}' |sed s/' '//g`"
+	ERR="`grep ^"Total Errors:" "$TMPFILE" |awk -F: '{print \$2}' |sed s/' '//g`"
 
 	if test "$WARN" = "0" && test "${ERR}" = "0"; then
-		echo "OK - Configuration check verified" > $NagiosCfgtestFile
+		echo "OK - Configuration check verified" > "$NagiosCfgtestFile"
 		@BIN_RM@ "$TMPFILE"
 		return 0
 	elif test "${ERR}" = "0"; then
 		# Write the errors to a file we can have a script watching for.
 		echo "WARNING: Warnings in config files - see log for details: $NagiosCfgtestFile" > $NagiosCfgtestFile
-		egrep -i "(^warning|^error)" "$TMPFILE" >> $NagiosCfgtestFile
+		egrep -i "(^warning|^error)" "$TMPFILE" >> "$NagiosCfgtestFile"
 		@BIN_RM@ "$TMPFILE"
 		return 0
 	else
 		# Write the errors to a file we can have a script watching for.
 		echo "ERROR: Errors in config files - see log for details: $NagiosCfgtestFile" > $NagiosCfgtestFile
-		egrep -i "(^warning|^error)" "$TMPFILE" >> $NagiosCfgtestFile
+		egrep -i "(^warning|^error)" "$TMPFILE" >> "$NagiosCfgtestFile"
 		cat "$TMPFILE"
 		exit 8
 	fi
@@ -132,7 +132,7 @@ check_config ()
 
 status_nagios ()
 {
-	if ps -p $NagiosPID > /dev/null 2>&1; then
+	if ps -p "$NagiosPID" > /dev/null 2>&1; then
 		return 0
 	else
 		return 1
@@ -150,17 +150,17 @@ printstatus_nagios ()
 
 killproc_nagios ()
 {
-	@BIN_KILL@ -s "$1" $NagiosPID
+	@BIN_KILL@ -s "$1" "$NagiosPID"
 }
 
 pid_nagios ()
 {
-	if test ! -f $NagiosRunFile; then
+	if test ! -f "$NagiosRunFile"; then
 		echo "No lock file found in $NagiosRunFile"
 		return 1
 	fi
 
-	NagiosPID=`head -n 1 $NagiosRunFile`
+	NagiosPID="`head -n 1 $NagiosRunFile`"
 }
 
 remove_commandfile ()
@@ -175,32 +175,32 @@ remove_commandfile ()
 	
 	# see http://unix.stackexchange.com/questions/335406/opening-named-pipe-blocks-forever-if-pipe-is-deleted-without-being-connected
 	
-	if [ -p $NagiosCommandFile ]; then
-		mv -f $NagiosCommandFile $NagiosCommandFile~
-		(dd if=$NagiosCommandFile~ count=0 2>/dev/null & echo -n "" >$NagiosCommandFile~ &)
+	if [ -p "$NagiosCommandFile" ]; then
+		mv -f "$NagiosCommandFile" "$NagiosCommandFile~"
+		(dd if=$NagiosCommandFile~ count=0 2>/dev/null & echo -n "" > "$NagiosCommandFile~" &)
 	fi
 	
-	@BIN_RM@ -f $NagiosCommandFile $NagiosCommandFile~
+	@BIN_RM@ -f "$NagiosCommandFile" "$NagiosCommandFile~"
 }
 
 
 # Check that nagios exists.
-if [ ! -f $NagiosBin ]; then
+if [ ! -f "$NagiosBin" ]; then
     echo "Executable file $NagiosBin not found. Exiting."
     exit 1
 fi
 
 # Check that nagios.cfg exists.
-if [ ! -f $NagiosCfgFile ]; then
+if [ ! -f "$NagiosCfgFile" ]; then
     echo "Configuration file $NagiosCfgFile not found. Exiting."
     exit 1
 fi
 
 # Get the lock_file from nagios.cfg
-NagiosRunFile=`sed -n -e 's/^lock_file=*//p' $NagiosCfgFile`
-if [ $? -ne 0 ]; then
+NagiosRunFile="`sed -n -e 's/^lock_file=*//p' $NagiosCfgFile`"
+if [ "$?" -ne "0" ]; then
 	# If there was a problem the use the value from when Core was compiled
-	NagiosRunFile=@subsyslockfile@
+	NagiosRunFile="@subsyslockfile@"
 fi
 
 # See how we were called.
@@ -211,8 +211,8 @@ case "$1" in
 
 		check_config
 
-		if test -f $NagiosRunFile; then
-			NagiosPID=`head -n 1 $NagiosRunFile`
+		if test -f "$NagiosRunFile"; then
+			NagiosPID="`head -n 1 $NagiosRunFile`"
 			if status_nagios; then
 				echo "another instance of nagios is already running."
 				exit 0
@@ -221,7 +221,7 @@ case "$1" in
 
 		su $NagiosUser -c "touch $NagiosVarDir/nagios.log $NagiosRetentionFile"
 		remove_commandfile
-		touch $NagiosRunFile
+		touch "$NagiosRunFile"
 		$NagiosBin -d $NagiosCfgFile
 
 		echo "done."
@@ -231,7 +231,7 @@ case "$1" in
 		echo -n "Stopping nagios: "
 
 		pid_nagios
-		if [ $? -eq 1 ]; then
+		if [ "$?" -eq "1" ]; then
 			exit 0
 		fi
 		killproc_nagios TERM
@@ -259,12 +259,12 @@ case "$1" in
 		fi
 
 		remove_commandfile
-		@BIN_RM@ -f $NagiosStatusFile $NagiosRunFile
+		@BIN_RM@ -f "$NagiosStatusFile" "$NagiosRunFile"
 		;;
 
 	status)
 		pid_nagios
-		if [ $? -eq 1 ]; then
+		if [ "$?" -eq "1" ]; then
 			exit 3
 		fi
 		printstatus_nagios
@@ -273,7 +273,7 @@ case "$1" in
 	checkconfig)
 		check_config
 
-		if [ $? -eq 0 ]; then
+		if [ "$?" -eq "0" ]; then
 			echo "OK."
 		else
 			echo "CONFIG ERROR!  Check your Nagios configuration."
@@ -291,7 +291,7 @@ case "$1" in
 	reload|force-reload)
 		check_config
 
-		if test ! -f $NagiosRunFile; then
+		if test ! -f "$NagiosRunFile"; then
 			$0 start
 		else
 			pid_nagios
