Unified variable syntax from: $var to ${var} because its less error-prone.

diff --git a/startup/default-init.in b/startup/default-init.in
--- a/startup/default-init.in
+++ b/startup/default-init.in
@@ -69,10 +69,10 @@ fi
 # Automate addition of RAMDISK based on environment variables
 USE_RAMDISK="${USE_RAMDISK:-0}"
 
-if test "$USE_RAMDISK" -ne 0 && test "$RAMDISK_SIZE"X != "X"; then
+if test "${USE_RAMDISK}" -ne 0 && test "${RAMDISK_SIZE}"X != "X"; then
 	ramdisk="$(mount |grep "${RAMDISK_DIR} type tmpfs")"
 
-	if [ "$ramdisk"X == "X" ]; then
+	if [ "${ramdisk}"X == "X" ]; then
 		if [ ! -d "${RAMDISK_DIR}" ]; then
 			mkdir -p -m 0755 "${RAMDISK_DIR}"
 
@@ -93,44 +93,44 @@ fi
 
 check_config ()
 {
-	if test "$checkconfig" != "true"; then
+	if test "${checkconfig}" != "true"; then
 		return 0
 	fi
 
 	echo -n "Running configuration check... "
 
-	@BIN_RM@ -f "$NagiosCfgtestFile";
+	@BIN_RM@ -f "${NagiosCfgtestFile}";
 
-	if test -e "$NagiosCfgtestFile"; then
-		echo "ERROR: Could not delete '$NagiosCfgtestFile'"
+	if test -e "${NagiosCfgtestFile}"; then
+		echo "ERROR: Could not delete '${NagiosCfgtestFile}'"
 		exit 8
 	fi
 
-	if ! su $NagiosUser -c "touch $NagiosCfgtestFile"; then
-		echo "ERROR: Could not create or update '$NagiosCfgtestFile'"
+	if ! su ${NagiosUser} -c "touch ${NagiosCfgtestFile}"; then
+		echo "ERROR: Could not create or update '${NagiosCfgtestFile}'"
 		exit 8
 	fi
 
 	TMPFILE="$(mktemp /tmp/.configtest.XXXXXXXX)"
-	$NagiosBin -vp $NagiosCfgFile > "$TMPFILE"
-	WARN="$(grep ^"Total Warnings:" "$TMPFILE" |awk -F: '{print \$2}' |sed s/' '//g)"
-	ERR="$(grep ^"Total Errors:" "$TMPFILE" |awk -F: '{print \$2}' |sed s/' '//g)"
+	${NagiosBin} -vp ${NagiosCfgFile} > "${TMPFILE}"
+	WARN="$(grep ^"Total Warnings:" "${TMPFILE}" |awk -F: '{print \$2}' |sed s/' '//g)"
+	ERR="$(grep ^"Total Errors:" "${TMPFILE}" |awk -F: '{print \$2}' |sed s/' '//g)"
 
-	if test "$WARN" == "0" && test "${ERR}" == "0"; then
-		echo "OK - Configuration check verified" > "$NagiosCfgtestFile"
-		@BIN_RM@ "$TMPFILE"
+	if test "${WARN}" == "0" && test "${ERR}" == "0"; then
+		echo "OK - Configuration check verified" > "${NagiosCfgtestFile}"
+		@BIN_RM@ "${TMPFILE}"
 		return 0
 	elif test "${ERR}" == "0"; then
 		# Write the errors to a file we can have a script watching for.
-		echo "WARNING: Warnings in config files - see log for details: $NagiosCfgtestFile" > $NagiosCfgtestFile
-		egrep -i "(^warning|^error)" "$TMPFILE" >> "$NagiosCfgtestFile"
-		@BIN_RM@ "$TMPFILE"
+		echo "WARNING: Warnings in config files - see log for details: ${NagiosCfgtestFile}" > ${NagiosCfgtestFile}
+		egrep -i "(^warning|^error)" "${TMPFILE}" >> "${NagiosCfgtestFile}"
+		@BIN_RM@ "${TMPFILE}"
 		return 0
 	else
 		# Write the errors to a file we can have a script watching for.
-		echo "ERROR: Errors in config files - see log for details: $NagiosCfgtestFile" > $NagiosCfgtestFile
-		egrep -i "(^warning|^error)" "$TMPFILE" >> "$NagiosCfgtestFile"
-		cat "$TMPFILE"
+		echo "ERROR: Errors in config files - see log for details: ${NagiosCfgtestFile}" > ${NagiosCfgtestFile}
+		egrep -i "(^warning|^error)" "${TMPFILE}" >> "${NagiosCfgtestFile}"
+		cat "${TMPFILE}"
 		exit 8
 	fi
 }
@@ -138,7 +138,7 @@ check_config ()
 
 status_nagios ()
 {
-	if ps -p "$NagiosPID" > /dev/null 2>&1; then
+	if ps -p "${NagiosPID}" > /dev/null 2>&1; then
 		return 0
 	else
 		return 1
@@ -148,7 +148,7 @@ status_nagios ()
 printstatus_nagios ()
 {
 	if status_nagios; then
-		echo "nagios (pid $NagiosPID) is running..."
+		echo "nagios (pid ${NagiosPID}) is running..."
 	else
 		echo "nagios is not running"
 	fi
@@ -156,17 +156,17 @@ printstatus_nagios ()
 
 killproc_nagios ()
 {
-	@BIN_KILL@ -s "$1" "$NagiosPID"
+	@BIN_KILL@ -s "$1" "${NagiosPID}"
 }
 
 pid_nagios ()
 {
-	if test ! -f "$NagiosRunFile"; then
-		echo "No lock file found in $NagiosRunFile"
+	if test ! -f "${NagiosRunFile}"; then
+		echo "No lock file found in ${NagiosRunFile}"
 		return 1
 	fi
 
-	NagiosPID="$(head -n 1 $NagiosRunFile)"
+	NagiosPID="$(head -n 1 ${NagiosRunFile})"
 }
 
 remove_commandfile ()
@@ -181,29 +181,29 @@ remove_commandfile ()
 	
 	# see http://unix.stackexchange.com/questions/335406/opening-named-pipe-blocks-forever-if-pipe-is-deleted-without-being-connected
 	
-	if [ -p "$NagiosCommandFile" ]; then
-		mv -f "$NagiosCommandFile" "$NagiosCommandFile~"
-		(dd if=$NagiosCommandFile~ count=0 2>/dev/null & echo -n "" > "$NagiosCommandFile~" &)
+	if [ -p "${NagiosCommandFile}" ]; then
+		mv -f "${NagiosCommandFile}" "${NagiosCommandFile}~"
+		(dd if=${NagiosCommandFile}~ count=0 2>/dev/null & echo -n "" > "${NagiosCommandFile}~" &)
 	fi
 	
-	@BIN_RM@ -f "$NagiosCommandFile" "$NagiosCommandFile~"
+	@BIN_RM@ -f "${NagiosCommandFile}" "${NagiosCommandFile}~"
 }
 
 
 # Check that nagios exists.
-if [ ! -f "$NagiosBin" ]; then
-    echo "Executable file $NagiosBin not found. Exiting."
+if [ ! -f "${NagiosBin}" ]; then
+    echo "Executable file ${NagiosBin} not found. Exiting."
     exit 1
 fi
 
 # Check that nagios.cfg exists.
-if [ ! -f "$NagiosCfgFile" ]; then
-    echo "Configuration file $NagiosCfgFile not found. Exiting."
+if [ ! -f "${NagiosCfgFile}" ]; then
+    echo "Configuration file ${NagiosCfgFile} not found. Exiting."
     exit 1
 fi
 
 # Get the lock_file from nagios.cfg
-NagiosRunFile="$(sed -n -e 's/^lock_file=*//p' $NagiosCfgFile)"
+NagiosRunFile="$(sed -n -e 's/^lock_file=*//p' ${NagiosCfgFile})"
 if [ "$?" -ne "0" ]; then
 	# If there was a problem the use the value from when Core was compiled
 	NagiosRunFile="@subsyslockfile@"
@@ -217,18 +217,18 @@ case "$1" in
 
 		check_config
 
-		if test -f "$NagiosRunFile"; then
-			NagiosPID="$(head -n 1 $NagiosRunFile)"
+		if test -f "${NagiosRunFile}"; then
+			NagiosPID="$(head -n 1 ${NagiosRunFile})"
 			if status_nagios; then
 				echo "another instance of nagios is already running."
 				exit 0
 			fi
 		fi
 
-		su $NagiosUser -c "touch $NagiosVarDir/nagios.log $NagiosRetentionFile"
+		su ${NagiosUser} -c "touch ${NagiosVarDir}/nagios.log ${NagiosRetentionFile}"
 		remove_commandfile
-		touch "$NagiosRunFile"
-		$NagiosBin -d $NagiosCfgFile
+		touch "${NagiosRunFile}"
+		${NagiosBin} -d ${NagiosCfgFile}
 
 		echo "done."
 		;;
@@ -268,7 +268,7 @@ case "$1" in
 		fi
 
 		remove_commandfile
-		@BIN_RM@ -f "$NagiosStatusFile" "$NagiosRunFile"
+		@BIN_RM@ -f "${NagiosStatusFile}" "${NagiosRunFile}"
 		;;
 
 	status)
@@ -302,7 +302,7 @@ case "$1" in
 	reload|force-reload)
 		check_config
 
-		if test ! -f "$NagiosRunFile"; then
+		if test ! -f "${NagiosRunFile}"; then
 			$0 start
 		else
 			pid_nagios
@@ -319,7 +319,7 @@ case "$1" in
 		;;
 
 	configtest)
-		$NagiosBin -vp $NagiosCfgFile
+		${NagiosBin} -vp ${NagiosCfgFile}
 		;;
 
 	*)
