Some more vars double quoted to prevent globbing and word splitting.

diff --git a/startup/default-init.in b/startup/default-init.in
--- a/startup/default-init.in
+++ b/startup/default-init.in
@@ -106,13 +106,13 @@ check_config ()
 		exit 8
 	fi
 
-	if ! su ${NagiosUser} -c "touch ${NagiosCfgtestFile}"; then
+	if ! su ${NagiosUser} -c "touch \"${NagiosCfgtestFile}\""; then
 		echo "ERROR: Could not create or update '${NagiosCfgtestFile}'"
 		exit 8
 	fi
 
 	TMPFILE="$(mktemp /tmp/.configtest.XXXXXXXX)"
-	${NagiosBin} -vp ${NagiosCfgFile} > "${TMPFILE}"
+	"${NagiosBin}" -vp "${NagiosCfgFile}" > "${TMPFILE}"
 	WARN="$(grep ^"Total Warnings:" "${TMPFILE}" |awk -F: '{print $2}' |sed s/' '//g)"
 	ERR="$(grep ^"Total Errors:" "${TMPFILE}" |awk -F: '{print $2}' |sed s/' '//g)"
 
@@ -122,13 +122,13 @@ check_config ()
 		return 0
 	elif test "${ERR}" == "0"; then
 		# Write the errors to a file we can have a script watching for.
-		echo "WARNING: Warnings in config files - see log for details: ${NagiosCfgtestFile}" > ${NagiosCfgtestFile}
+		echo "WARNING: Warnings in config files - see log for details: ${NagiosCfgtestFile}" > "${NagiosCfgtestFile}"
 		egrep -i "(^warning|^error)" "${TMPFILE}" >> "${NagiosCfgtestFile}"
 		@BIN_RM@ "${TMPFILE}"
 		return 0
 	else
 		# Write the errors to a file we can have a script watching for.
-		echo "ERROR: Errors in config files - see log for details: ${NagiosCfgtestFile}" > ${NagiosCfgtestFile}
+		echo "ERROR: Errors in config files - see log for details: ${NagiosCfgtestFile}" > "${NagiosCfgtestFile}"
 		egrep -i "(^warning|^error)" "${TMPFILE}" >> "${NagiosCfgtestFile}"
 		cat "${TMPFILE}"
 		exit 8
@@ -166,7 +166,7 @@ pid_nagios ()
 		return 1
 	fi
 
-	NagiosPID="$(head -n 1 ${NagiosRunFile})"
+	NagiosPID="$(head -n 1 "${NagiosRunFile}")"
 }
 
 remove_commandfile ()
@@ -203,7 +203,7 @@ if [ ! -f "${NagiosCfgFile}" ]; then
 fi
 
 # Get the lock_file from nagios.cfg
-NagiosRunFile="$(sed -n -e 's/^lock_file=*//p' ${NagiosCfgFile})"
+NagiosRunFile="$(sed -n -e 's/^lock_file=*//p' "${NagiosCfgFile}")"
 if [ "$?" -ne "0" ]; then
 	# If there was a problem the use the value from when Core was compiled
 	NagiosRunFile="@subsyslockfile@"
@@ -218,17 +218,17 @@ case "$1" in
 		check_config
 
 		if test -f "${NagiosRunFile}"; then
-			NagiosPID="$(head -n 1 ${NagiosRunFile})"
+			NagiosPID="$(head -n 1 "${NagiosRunFile}")"
 			if status_nagios; then
 				echo "another instance of nagios is already running."
 				exit 0
 			fi
 		fi
 
-		su ${NagiosUser} -c "touch ${NagiosVarDir}/nagios.log ${NagiosRetentionFile}"
+		su ${NagiosUser} -c "touch \"${NagiosVarDir}/nagios.log\" \"${NagiosRetentionFile}\""
 		remove_commandfile
 		touch "${NagiosRunFile}"
-		${NagiosBin} -d ${NagiosCfgFile}
+		"${NagiosBin}" -d "${NagiosCfgFile}"
 
 		echo "done."
 		;;
@@ -319,7 +319,7 @@ case "$1" in
 		;;
 
 	configtest)
-		${NagiosBin} -vp ${NagiosCfgFile}
+		"${NagiosBin}" -vp "${NagiosCfgFile}"
 		;;
 
 	*)
